spring:
  profiles:
    active: dev

mybatis:
  mapperLocations: classpath*:com/example/poiutis/dao/**/*.xml
  typeAliasesPackage: classpath*:com.example.poiutis.model
  typeHandlersPackage: classpath*:com.example.poiutis.handler.enums

#日志相关设置
log_base: C:\\TEST
app_name: poiutils
console_level: INFO

